# locals {
#   global_mock_outputs = {

#     alb_dns_name = ""
#     alb_sg_id = ""
#     client_sg_id = ""
#     cloudfront_aliases = ""
#     cloudfront_domain_name = ""
#     cloudfront_hosted_zone_id = ""
#     db_endpoint = ""
#     db_secret_name = ""
#     db_sg_id = ""
#     endpoint_address = ""
#     igw_id = ""
#     internal_alb_dns_name = ""
#     internal_alb_sg_id = ""
#     internal_tg_arn = ""
#     panda_bucket_name = ""
#     pri_rt_a_id = ""
#     pri_rt_b_id = ""
#     pri_sub_3a_id = ""
#     pri_sub_4b_id = ""
#     pri_sub_5a_id = ""
#     pri_sub_6b_id = ""
#     pri_sub_7a_id = ""
#     pri_sub_8b_id = ""
#     project_name = ""
#     pub_sub_1a_id = ""
#     pub_sub_2b_id = ""
#     s3_ssm_cw_instance_profile_name = ""
#     server_sg_id = ""
#     tg_arn = ""
#     vpc_cidr_block = ""
#     vpc_id = ""

#   }
# }

locals {
  global_mock_outputs = {
    alb_dns_name                = "mock-alb.example.com"
    alb_sg_id                   = "sg-aaaa1111"
    client_sg_id                = "sg-bbbb2222"
    acm_certificate_domain_name = "devsandbox.space"
    # hosted_zone_name     = "devsandbox.space"
    cloudfront_aliases              = ["www.devsandbox.space"]
    cloudfront_domain_name          = "d123456abcdef8.cloudfront.net"
    cloudfront_hosted_zone_id       = "Z2FDTNDATAQYW2"
    db_endpoint                     = "mock-db-instance.cle6abcd.us-east-1.rds.amazonaws.com"
    db_secret_name                  = "mock-db-secret"
    db_sg_id                        = "sg-cccc3333"
    endpoint_address                = "mock-endpoint.amazonaws.com"
    igw_id                          = "igw-aaaa1111"
    internal_alb_dns_name           = "internal-alb.example.internal"
    internal_alb_sg_id              = "sg-dddd4444"
    internal_tg_arn                 = "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/mock-internal-tg/abcd1234"
    panda_bucket_name               = "mock-panda-bucket"
    pri_rt_a_id                     = "rtb-aaaa1111"
    pri_rt_b_id                     = "rtb-bbbb2222"
    pri_sub_3a_id                   = "subnet-aaaa1111"
    pri_sub_4b_id                   = "subnet-bbbb2222"
    pri_sub_5a_id                   = "subnet-cccc3333"
    pri_sub_6b_id                   = "subnet-dddd4444"
    pri_sub_7a_id                   = "subnet-eeee5555"
    pri_sub_8b_id                   = "subnet-ffff6666"
    project_name                    = "mock-project"
    pub_sub_1a_id                   = "subnet-aaaa9999"
    pub_sub_2b_id                   = "subnet-bbbb8888"
    s3_ssm_cw_instance_profile_name = "mock-ssm-instance-profile"
    server_sg_id                    = "sg-eeee5555"
    tg_arn                          = "arn:aws:elasticloadbalancing:us-east-1:123456789012:targetgroup/mock-tg/xyz9876"
    vpc_cidr_block                  = "10.0.0.0/16"
    vpc_id                          = "vpc-1234567890abcdef0"
    frontend_ami_id                 = "ami-safdasdsadfasf"
    backend_ami_id                  = "ami-safdasdsadfasf"
    acm_certificate_arn             = "arn:aws:iam::187416307283:server-certificate/test_cert_rab3wuqwgja25ct3n4jdj2tzu4"


  }
}
